.gitignore
Jenkinsfile
jq-filter.txt

This fixes https://github.com/mozilla/wpt-api/issues/5, pretty much.
Ad-hoc build: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt-api.fxa-perf.adhoc/63/console
@davehunt pretty please, r?

Fix build by passing in jq's query from a file, add .gitignore, and pare runs down to 5

---

.gitignore
Jenkinsfile

I'm having issues even trying to run this in our Jenkins ad-hoc job, but hopefully a rebase or something will explain it

[WIP] Add no cache docker

---

Jenkinsfile
jq-filter.txt

@davehunt @philbooth r/thoughts?
Passing build here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt-api.fxa-perf.adhoc/
Full output: https://gist.github.com/stephendonner/1ecbb4745c08db2bf6aef5bbd2bd96f0

Add more metrics fields

---

jq-filter.txt

Ad-hoc build here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt-api.fxa-perf.adhoc/101/

Use median for results, and use render and visualComplete metrics

---

.pyup.yml
README.md

r?  @mozilla/firefox-test-engineering

Add pyup support, with badges

---

README.md

Fixes https://github.com/mozilla/wpt-api/issues/4 in time for the All-Hands demos and hack sessions; more to come!
@mozilla/firefox-test-engineering r?

Update docs/README to reflect current progress and status

---

README.md

Casting r? to @mozilla/firefox-test-engineering

Actually add, you know, the project's title to README

---

Jenkinsfile
commands.txt
send_to_datadog.py

Fixes https://github.com/mozilla/wpt-api/issues/60

Add facebook.com tests to metrics

---

Pipfile.lock

Revert "Scheduled weekly dependency update for week 36"

---

.pyup.yml
README.md

@davehunt @jrbenny35 @mozilla/firefox-test-engineering r?
https://github.com/stephendonner/wpt-api/tree/967f4f5ca09586ebaf2c3a1b9fecacd80fddbe62

Switch from pyup.io to dependabot

---

README.md

@mozilla/firefox-test-engineering r?

Add screenshot of DataDog results, to help visualize

---

README.md

@mozilla/firefox-test-engineering r?

Add screenshot of DataDog, to help illustrate

---

commands.txt

@davehunt I'm landing this (without formal review) after a good, lengthy discussion @jbuck and I had.  For now, we've scaled to 4 c5.xlarge wptagent instances/drivers, and are trying to capacity-test and plan, a bit

Add 20 more Alexa Topsites; we are now at 30

---

docs/index.md

This is to enable building our new Read The Docs instance (yay!): https://readthedocs.org/projects/mozilla-wpt-api-docs/
I'm going to merge, this is just FYI, for now.
/cc @davehunt @jbuck

Nascent /docs

---

Jenkinsfile

@davehunt lots more we could (and should) do, here, but I wanted to start getting the basic in; r?

Add IRC notification on failure

---

Jenkinsfile

This should fix https://github.com/mozilla/wpt-api/issues/127
@davehunt r?

Add ansiColor to build output

---

docs/index.md

@davehunt another round/checkpoint - still much room for improvements, but it's got legs!

Docs round two

---

send_to_datadog.py

Fix F401: 'pprint.pprint imported but unused' warning

---

Jenkinsfile

Should fix https://github.com/mozilla/wpt-api/issues/152
@davehunt r?

Add --medianvideo, to save the median run's video

---

README.md

More to come, over in https://github.com/mozilla/wpt-api/tree/master/docs (soonish).

Readthedocs badge and other, good cleanup

---

README.md

Credits where credits are due (more always pending)

---

Jenkinsfile

From https://github.com/marcelduran/webpagetest-api/tree/9c4d4d89aa9637319bdc4d170211e19abafafda7#test-works-for-test-command-only:
```
-I, --noimages: disable screen shot[sic] capturing
```
/cc @davehunt @stuartphilp

Disable screenshot capturing,  via --noimages

---

docs/_templates/layout.html

Just trying https://stackoverflow.com/questions/44793811/change-the-colors-of-the-sphinx-read-the-docs-theme

Try changing layout-page theme

---

Jenkinsfile

@davehunt this appears to be the -- or close to -- proverbial nail in the sensitive-content considerations and tweaks, but I'm still, of course, going to look further.
/cc @jbuck @davehunt do either of you know if we should also be worried about purging/asking to be purged, from S3, etc., before this-set-of-fixes landed?

Remove Speed Index as median

---

Jenkinsfile

Let's see how this fares, performance-wise.

Disables (web) optimization checks we don't need

---

docs/index.md

This addresses https://github.com/mozilla/wpt-api/issues/159; closing.

Added timeouts and filled in metrics a bit

---

Dockerfile

Passed locally and via ad-hoc build: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt.adhoc/91/console

Upgrade Python version in Dockerfile base image from 3.6 to 3.7

---

.travis.yml
Pipfile
Pipfile.lock

Looking good locally! (Phew)
```
Stephens-MacBook-Pro:wpt-api stephendonner$ pipenv update --python 3.7
Virtualenv already exists!
Removing existing virtualenv...
Creating a virtualenv for this project...
Pipfile: /Users/stephendonner/wpt-api/Pipfile
Using /usr/local/opt/python/libexec/bin/python (3.7.2) to create virtualenv...
⠙ Creating virtual environment...Using base prefix '/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/stephendonner/.local/share/virtualenvs/wpt-api-mC8QJCC2/bin/python3.7
Also creating executable in /Users/stephendonner/.local/share/virtualenvs/wpt-api-mC8QJCC2/bin/python
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /usr/local/opt/python/libexec/bin/python
✔ Successfully …
```

Update Travis, Pipfile, and its Pipfile.lock for Python 3.7.2

---

.pre-commit-config.yaml
.travis.yml
Pipfile
Pipfile.lock
README.md
send_to_datadog.py

Passing adhoc build here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt.adhoc/215/console
@jrbenny35 @davehunt r?  Thanks!

Paint it black
