mozilla/wpt-api

- Jenkinsfile
This is temporary, and we'll work out the best config option for passing in multiple URLs, later.
For now, this fix for https://github.com/mozilla/wpt-api/issues/6 is slightly cleaner, and makes the command-line easier to read/manage, etc.
Passing ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt-api.fxa-perf/73/console and here: https://gist.github.com/stephendonner/8d35f62cfd56c5e099adc1211e8ed303
@philbooth @davehunt @soulgalore r?
> Abstract out and move PAGE_URL to env, rather than hard-coding it

- Jenkinsfile
This lays the ground work for https://github.com/mozilla/wpt-api/issues/5
Passing ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt-api.fxa-perf.adhoc/33/
I still need to write out and archive ```stats.json``` or whatever we're going to (temporarily) call the new, output perf-metrics file.
> Use jq to filter out desired perf metrics from JSON-results file

- jq-filter.txt
> Remove TTIMeasurementEnd, which is Chrome-only, and null in Firefox

- .dockerignore
- .gitignore
- Dockerfile
- Jenkinsfile
- envcat
- jq-filter.txt
- send_to_datadog.py
@mozilla/firefox-test-engineering r?
Fixes https://github.com/mozilla/wpt-api/issues/16 and obviates/fixes https://github.com/mozilla/wpt-api/issues/22 (and, likely, a bunch more!)
While there is still quite a bit of cleanup and extending to do, I'm very, very happy that this is pretty lightweight, readable, etc.
**_The eagle has landed!_**
/cc @philbooth @muffinresearch @@onkeltom @digitarald @kannanvijayan @stuartphilp oh, and @jbuck, so he knows why I'm pestering him about the wpt-api instance, of late :-)
Edit: Glorious screenshot of plotted metric data in DataDog, gratuitously included for satisfaction.
> Filter, format, and send selected, desired Firefox Accounts perf metrics to DataDog, via Jenkins

- Jenkinsfile
- README.md
- send_to_datadog.py
r?  @mozilla/firefox-test-engineering 
Passing ad-hoc job here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt-api.fxa-perf.adhoc/5126/
Also, screenshot of this "new" metric working grandly, in DataDog 🎉 
/cc @philbooth (and a huge thanks, again, to @jbuck <3)
> Use us-east-1-linux location, to use timeToNonBlankPaint (firstPaint)

- README.md
Fix https://github.com/mozilla/wpt-api/issues/59 by updating README to be ```alexa-topsites``` branch workflow-specific/relevant.
@mozilla/firefox-test-engineering @karlht @jgmize r?
> Update README doc with alexa-topsites-specific context/content

- README.md
- send_to_datadog.py
This makes use of a relatively new metric Time to DOMContentFlushed, aka ```DOMContentFlushed```, from https://bugzilla.mozilla.org/show_bug.cgi?id=1457325.
It depends on https://github.com/mozilla-services/webpagetest-settings/pull/5 being in and the internal webpagetest instance being updated, before using.
@mozilla/firefox-test-engineering @philbooth @jbuck r?
> Add Time to DOMContentFlushed metric

- commands.txt
Fixes https://github.com/mozilla/wpt-api/issues/101; but I'd like a general consensus or at least awareness from the team at large, that this is OK/happening, first.
EDIT: Update - nobody yet has objected, and I have a couple approvals already (Stuart, folks in #perfteam).
> Add --keepua to preserve all original browsers' user-agents

- commands.txt
Reverts mozilla/wpt-api#111
This broke, with this error, which I can't figure out - wanted to get a few good runs in before we can look at this issue more closely/together.
```
04:23:50 [wpt-api.perf.alexa-topsites] Running shell script
04:23:50 + /usr/src/app/bin/webpagetest batch commands.txt
Post stage
05:49:29 /usr/src/app/bin/webpagetest:228
05:49:29         results.length ? JSON.stringify(results, null, 2) : '',
05:49:29                               ^
05:49:29 
05:49:29 RangeError: Invalid string length
05:49:29     at join (native)
05:49:29     at Object.stringify (native)
05:49:29     at checkDone (/usr/src/app/bin/webpagetest:228:31)
05:49:29     at checkError (/usr/src/app/bin/webpagetest:236:5)
05:49:29     at aggregate (/usr/src/app/bin/webpagetest:241:5)
05:49:29     at …
```
> Revert "Add 20 more Alexa Topsites; we are now at 30"

- Jenkinsfile
@davehunt r?  Only partially addresses https://github.com/mozilla/wpt-api/issues/144 - email alerts are easy to add, but due to being 50 single tests, could be catastrophic to our inboxes; if that's not a concern for you, others, I'll go ahead and add it, too.
Cheers.
> Add IRC and email alerts for build failures

- Jenkinsfile
@davehunt r?
Addresses https://github.com/mozilla/wpt-api/issues/148.
> Enable video capture, so we get filmstrips and the raw test-run video

- Jenkinsfile
@davehunt r?
Tested in https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt/job/vimeo/133/console, manually, using Replay.
> Add 'webpagetest' label to match jobs + nodes

- Jenkinsfile
See https://www.webpagetest.org/forums/archive/index.php?thread-12060.html and ```--priority``` here: https://github.com/marcelduran/webpagetest-api/blob/9c4d4d89aa9637319bdc4d170211e19abafafda7/README.md#test-works-for-test-command-only
@davehunt r, thoughts?  @soulgalore
> Add (higher) --priority as 1 (rather than 5), for API-initiated tests

- metrics.json
This is a corollary to https://github.com/mozilla-services/cloudops-deployment/pull/2824.
Adding in that calculation -- which is the same as Raptor's (see https://bugzilla.mozilla.org/show_bug.cgi?id=1504013#c13), which inspired these PRs.
@davehunt @rwood-moz r?
> Add Fx-custom pageLoadTime metric

- Jenkinsfile
See https://github.com/mozilla/wpt-api/issues/166 - tries to help address various ```twitch.tv``` test-run timeouts (on Firefox Nightly).
/cc @jbuck + @davehunt just FYI
> Adds a higher --timeout from (default) 600 sec -> 900 seconds

- Jenkinsfile
N.B. - we still need my next PR, which removes ```--median SpeedIndex```, as passing that overrides the defaults, as that metric relies entirely, I believe on the video, and needs to retain it (for a bit), post-process, and analyze the test-run video.
See https://www.webpagetest.org/forums/showthread.php?tid=12830&pid=22972#pid22972
/cc @davehunt
> Remove --video, so we stop trying to saving captured video + filmstrips

- Jenkinsfile
- send_to_datadog.py
Unfortunately, response bodies for text resources (raw CSS, JavaScript, etc., files) aren't working 100% in Firefox.  I'll work through the issue(s) with Pat Meenan and others, and then we'll re-enable.
I imagine this will save us just a bit of overhead/post-processing time, at least, too.
> Remove response bodies

- Jenkinsfile
This is safe, and is only the first step in https://github.com/mozilla/wpt-api/issues/84 towards public-instance mobile runs called via our Jenkins jobs, but we should be able to iterate quickly.
> Part 1 of Issue #84: add PUB_WPT_API_KEY to Jenkins' environment block

- send_to_telemetry.py
This patch allows us to ignore when median or standardDeviation are missing from the results. This allows the JSON to be generated, and the following stages to execute, but will not alert us to the issue. I think this is fine, as the schema allows for these to be missing, but if the cause is a crash that we should be aware of then perhaps we need a way to be notified of such issues.
> Allow for median/standardDeviation to be missing from the results

- Jenkinsfile
The ENTRYPOINT in the Dockerfile for webpagetest-api is causing issues with the latest version of Jenkins and docker workflow plugins. I've forked the repo and removed the entrypoint, and reference the fork/branch here. It seems to resolve our issues.
> Work around issues with latest Jenkins and plugins

- send_to_telemetry.py
The new telemetry pipeline in GCP is more strict about requiring that
submissions include a valid UUID as the document_id in the URI.
Specifically, the pipeline requires the standard 36-character representation
that includes dashes.
Currently, wpt pings are identified as invalid and sent to error output in the
GCP telemetry pipeline due to using 32-character UUIDs.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1597217
> Use standard 36-character UUID representation for telemetry
